### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by cdupont** [Waziup/Socialbackend#6]
Using a wrong user_id yields a null pointer exception:
```
curl -H "Content-Type: application/json" -X POST -d '{"user_id":"test","channel":"twitter", "message": "Hello from Waziup social media API"}' http://localhost:8080/SocialBackend/socials

org.jboss.resteasy.spi.UnhandledException: java.lang.NullPointerException                                   
at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:78)   
at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:222)                                                                                                             
```

**Comment by pandaconstantin** [comment]
Solved !

**Comment by cdupont** [comment]
thanks, closing

**Comment by pandaconstantin** [comment]
Solved !
